# Generated by Django 5.2.3 on 2025-06-27 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "csv_file",
                    models.FileField(
                        upload_to="csv_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv"]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("lecture", "Lecture"), ("lab", "Lab")], max_length=20
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=10)),
                ("course_number", models.CharField(max_length=10)),
                ("section", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("days", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("instructor", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date_range", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "schedule_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_kiosk.schedulefile",
                    ),
                ),
            ],
            options={
                "ordering": ["days", "start_time"],
            },
        ),
    ]
